modLoader="javafml"
loaderVersion="[3,)"
issueTrackerURL="https://github.com/Mrbysco/DoAFlip/issues"
license="MIT"

[[mods]]
modId="doaflip"
version="${file.jarVersion}"
displayName="Do A Flip!"
displayURL="https://www.curseforge.com/minecraft/mc-mods/do-a-flip"
authors="Mrbysco, ShyNieke"
description='''
Makes mobs do a flip!
'''

[[dependencies.doaflip]]
modId="minecraft"
type="required"
versionRange="[1.20.6,1.21)"
ordering="NONE"
side="BOTH"
[[mixins]]
config="doaflip.mixins.json"