
#Flip settings
[Flip]
	#The chance of a flip happening when a mob falls from a high enough distance [0.0 = 0%, 0.1 = 10%, 1.0 = 100%] (Default: 0.35)
	#Range: 0.0 ~ 1.0
	flipChance = 0.35
	#When enabled turns the flippingMobs option into a blacklist [default: true]
	invertMobs = true
	#Defines a list of mobs that can flip when falling from a high enough distance [Format: modid:entity]
	flippingMobs = ["minecraft:bat", "minecraft:armor_stand", "minecraft:ender_dragon", "minecraft:wither"]

