modLoader="javafml"
loaderVersion="[46,)"
issueTrackerURL="https://github.com/Mrbysco/DoAFlip/issues"
license="MIT"

[[mods]]
modId="doaflip"
version="${file.jarVersion}"
displayName="Do A Flip!"
displayURL="https://www.curseforge.com/minecraft/mc-mods/do-a-flip"
logoFile="logo.png"
authors="Mrbysco, ShyNieke"
description='''
Makes mobs do a flip!
'''

[[dependencies.doaflip]]
modId="minecraft"
mandatory=true
versionRange="[1.20,1.21)"
ordering="NONE"
side="BOTH"